[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "yeast_mito_simul" 
version = "2.0"

[tool.setuptools]
packages = ["yeast_mito_segregation"] 